/**
 * GENERATED by scripts/emit-schemas.ts — do not edit.
 *
 * The `.default()` value of every top-level field, per section type. Applied
 * at the runtime boundary (lib/content/guard.ts) so CMS content that omits an
 * optional list does not reach a component as `undefined`.
 */
export const SECTION_DEFAULTS: Record<string, Record<string, unknown>> = {
  "hero-map": {
    "actions": [],
    "marketSource": "all",
    "searchLabel": "Find your market",
    "searchPlaceholder": "Search 46 markets",
    "searchEmptyLabel": "No market by that name. Try a region — Africa, Asia Pacific.",
    "bulletinLabel": "Health authority bulletin",
    "bulletin": [],
    "authorityLabel": "Regulatory authorities",
    "ticker": []
  },
  "page-head": {
    "actions": []
  },
  "sub-capability-grid": {
    "items": []
  },
  "metric-row": {
    "items": []
  },
  "faq-accordion": {
    "items": []
  },
  "country-head": {
    "eyebrow": "Market",
    "localTimeLabel": "Local time",
    "showLocator": true,
    "actions": []
  },
  "capability-status": {
    "eyebrow": "Capability coverage",
    "notes": {}
  },
  "job-list": {
    "source": "all",
    "emptyMessage": "No openings are listed right now."
  },
  "job-detail": {
    "applyLabel": "Apply for this role",
    "responsibilitiesLabel": "What you will do",
    "requirementsLabel": "What you will bring"
  },
  "article-grid": {
    "showFilters": true,
    "allLabel": "All",
    "emptyMessage": "Nothing published here yet."
  },
  "article-head": {
    "backLabel": "← All insights",
    "backHref": "/insights"
  },
  "explore-journeys": {
    "linkLabel": "Explore",
    "items": [],
    "showCertifications": false
  },
  "statement": {
    "actions": []
  },
  "industry-index": {
    "countLabel": "types",
    "items": []
  },
  "market-directory": {
    "searchLabel": "Search for a country",
    "searchPlaceholder": "Start typing a country or region…",
    "countryColumnLabel": "Market",
    "regionColumnLabel": "Region",
    "emptyLabel": "No market matches that search.",
    "marketSource": "all"
  },
  "region-cards": {
    "regions": []
  },
  "process-grid": {
    "stages": []
  },
  "pill-row": {
    "items": []
  },
  "value-grid": {
    "items": []
  },
  "proof-billboard": {
    "cases": []
  },
  "insight-feed": {
    "listLinkLabel": "View all",
    "listLinkHref": "/insights",
    "items": [],
    "featuredSlug": "",
    "limit": 4
  },
  "contact-split": {
    "fields": [],
    "routes": []
  },
  "case-study-index": {
    "source": "all",
    "readLabel": "Read the case study"
  },
  "case-study-head": {
    "backLabel": "← All case studies"
  },
  "case-study-body": {
    "scenarioLabel": "Scenario",
    "solutionLabel": "Solution",
    "resultLabel": "Result",
    "pagerLabel": "Next case study"
  }
};
