/**
 * Build-time only. Converts the Zod section schemas into JSON Schema and
 * writes them to public/section-schemas.json.
 *
 * That file is the contract three other things build against:
 *   - the Creator editor widget, which renders its form fields from it
 *   - Catalyst, which validates a revision against it before publishing
 *   - the CMS field spec handed to the client
 *
 * Because they all derive from the same schemas the components are typed
 * from, the editor's fields and the renderer's props cannot drift apart.
 *
 * Run:  npx tsx scripts/emit-schemas.ts     (wired into `npm run build`)
 *
 * Zod is a devDependency and is imported ONLY here and in the schema.ts
 * files. Nothing in the request path imports it — see lib/content/guard.ts.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { sectionSchema, pageSchema, SECTION_SCHEMAS } from "../lib/schema/section";
import { REGISTERED_TYPES } from "../components/sections/registry";

/**
 * Per-type field DEFAULTS, pulled out of the emitted JSON Schema.
 *
 * WHY THIS EXISTS. Every `.default([])` in a section schema is applied by Zod
 * at PARSE time — and Zod deliberately never runs in the request path. With
 * fixtures that was invisible, because a fixture author always writes the
 * whole object. CMS content is different: an editor who adds no buttons sends
 * no `actions` key at all, the component reads `actions.length`, and the page
 * crashes.
 *
 * That is exactly what happened the first time a real Creator page rendered.
 *
 * So the defaults are extracted at build time and applied at the boundary in
 * lib/content/guard.ts. Top level only, which is the level `.default()` is
 * used at across all 25 schemas — and the level the crash happens at.
 */
type JsonSchemaObject = { properties?: Record<string, { default?: unknown }> };

function defaultsFor(schema: (typeof SECTION_SCHEMAS)[number]): Record<string, unknown> {
  const json = z.toJSONSchema(schema, { io: "input" }) as JsonSchemaObject;
  const out: Record<string, unknown> = {};
  for (const [key, prop] of Object.entries(json.properties ?? {})) {
    if (prop && Object.hasOwn(prop, "default")) out[key] = prop.default;
  }
  return out;
}

const sectionDefaults: Record<string, Record<string, unknown>> = {};
for (const schema of SECTION_SCHEMAS) {
  const literal = (schema.shape.type as unknown as { value: string }).value;
  const defaults = defaultsFor(schema);
  if (Object.keys(defaults).length > 0) sectionDefaults[literal] = defaults;
}

writeFileSync(
  join(process.cwd(), "lib", "schema", "section-defaults.generated.ts"),
  `/**
 * GENERATED by scripts/emit-schemas.ts — do not edit.
 *
 * The \`.default()\` value of every top-level field, per section type. Applied
 * at the runtime boundary (lib/content/guard.ts) so CMS content that omits an
 * optional list does not reach a component as \`undefined\`.
 */
export const SECTION_DEFAULTS: Record<string, Record<string, unknown>> = ${JSON.stringify(
    sectionDefaults,
    null,
    2,
  )};
`,
);

const out = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  generatedAt: new Date().toISOString(),
  sectionTypes: REGISTERED_TYPES,
  page: z.toJSONSchema(pageSchema, { io: "input" }),
  section: z.toJSONSchema(sectionSchema, { io: "input" }),
  sectionDefaults,
};

mkdirSync(join(process.cwd(), "public"), { recursive: true });
writeFileSync(
  join(process.cwd(), "public", "section-schemas.json"),
  JSON.stringify(out, null, 2) + "\n",
);

console.log(
  `[emit-schemas] ${REGISTERED_TYPES.length} section types → public/section-schemas.json`,
);
